### ISSUE TITLE
incorrect src filter for images

### ISSUE THREAD

**Issue by danielwix** [wix/wix-gruntfile#35]
No images are copied to _debug, because there are no images with *.js format.
Should have been:
{
          expand: true,
          cwd: '.tmp/images/',
          src: ['**/*.*'],
          dest: 'dist/_debug/images'
        }, {
          expand: true,
          cwd: 'app/images/',
          src: ['**/*.*'],
          dest: 'dist/_debug/images'
        }

instead of 
{
          expand: true,
          cwd: '.tmp/images/',
          src: ['**/*.js'],
          dest: 'dist/_debug/images'
        }, {
          expand: true,
          cwd: 'app/images/',
          src: ['**/*.js'],
          dest: 'dist/_debug/images'
        }

**Comment by flyingjamus** [comment]
fixed
